# Azure Pipelines to build & publish project exter_demo
# Language: Go
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: 'exter-demo'
  apVersion: '1.0'
  goVersion: '1.13.14'
  goBuiltAppName: 'main'

stages:
  - stage: build
    displayName: Build project
    jobs:
      - job: build
        displayName: Build project
        steps:
          - task: GoTool@0
            displayName: Prepare Go env
            inputs:
              version: '$(goVersion)'
          - task: Go@0
            displayName: Go build
            inputs:
              command: 'build'
              arguments: '-o $(goBuiltAppName)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          - task: CopyFiles@2
            displayName: Copy build to binary
            inputs:
              sourceFolder: '$(System.DefaultWorkingDirectory)'
              targetFolder: '$(Build.BinariesDirectory)'
              contents: |
                '$(goBuiltAppName)'
                *.md
          - script: |
              echo Build.BinariesDirectory: '$(Build.BinariesDirectory)'
              echo Build.ArtifactStagingDirectory: '$(Build.ArtifactStagingDirectory)'
              echo Build.BuildId: '$(Build.BuildId)'
              ls -la '$(Build.BinariesDirectory)'
              pwd && ls -la
