# Azure Pipelines to build & publish project exter_demo
# Language: Go
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: 'exter-demo'
  appVersion: '1.0'
  goVersion: '1.13.14'
  goBuiltAppName: 'main'

stages:
  - stage: build
    displayName: Build project
    jobs:
      - job: build_and_test
        displayName: Build project and run tests
        steps:
          - task: GoTool@0
            displayName: Prepare Go env
            inputs:
              version: '$(goVersion)'
          - task: Go@0
            displayName: Go build
            inputs:
              command: 'build'
              arguments: '-o $(goBuiltAppName)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          - task: Go@0
            displayName: Go test
            inputs:
              command: 'test'
              arguments: '-v --cover'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          - task: CopyFiles@2
            displayName: Copy build to binary
            inputs:
              sourceFolder: '$(System.DefaultWorkingDirectory)'
              targetFolder: '$(Build.BinariesDirectory)'
              contents: |
                $(goBuiltAppName)
                *.md
          - task: PublishPipelineArtifact@1
            displayName: Publish artifact
            inputs:
              targetPath: '$(Build.BinariesDirectory)'
              artifactName: '$(appName)'

  - stage: build_publish_docker
    displayName: Build and publish Docker image
    dependsOn: build
    jobs:
      - job: build_publish_docker
        displayName: Build and publish Docker image
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: Prepare artifact
            inputs:
              artifact: '$(appName)'
              path: '$(Build.ArtifactStagingDirectory)'
          - script: |
              ls -la '$(Build.ArtifactStagingDirectory)'
