# Azure Pipelines to build & publish project exter_demo
# Language: Go
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  goVersion: '1.13.14'
  imageVersion: '1.0'

stages:
  - displayName: Build
    jobs:
      - job: build
        displayName: Build project
        steps:
          - task: GoTool@0
            inputs:
              version: '$(goVersion)'
          - task: Go@0
            inputs:
              command: 'build'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
